### ISSUE TITLE
need eagle library for SHT3x

### ISSUE THREAD

**Issue by mjdietzx** [Sensirion/SmartGadget-Hardware#1]
is there already one available. if not can you publish?

thanks,
Mike

**Comment by ElnumaM** [comment]
Hi Mike,

Unfortunately Sensirion doesn't provide design libraries for the SHT3x.

I've found a design file which has not been verified by Sensirion:
http://www.eevblog.com/forum/eagle/i-just-finished-making-my-first-eagle-part-the-sht31-dis-temp-humid-sensor/

I hope that helps.

Regards,
Manuel

**Comment by mjdietzx** [comment]
Thank you!
